/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routes/__root'
import { Route as ProfileRouteImport } from './../../app/routes/profile'
import { Route as AboutRouteImport } from './../../app/routes/about'
import { Route as IndexRouteImport } from './../../app/routes/index'
import { Route as ProfileIndexRouteImport } from './../../app/routes/profile.index'
import { Route as ProfileSettingsRouteImport } from './../../app/routes/profile.settings'
import { Route as ProfileFavoriteMessagesRouteImport } from './../../app/routes/profile.favorite-messages'
import { Route as HashtagHashtagRouteImport } from './../../app/routes/hashtag.$hashtag'
import { Route as AnswersAnswerIdRouteImport } from './../../app/routes/answers.$answerId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileFavoriteMessagesRoute = ProfileFavoriteMessagesRouteImport.update({
  id: '/favorite-messages',
  path: '/favorite-messages',
  getParentRoute: () => ProfileRoute,
} as any)
const HashtagHashtagRoute = HashtagHashtagRouteImport.update({
  id: '/hashtag/$hashtag',
  path: '/hashtag/$hashtag',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersAnswerIdRoute = AnswersAnswerIdRouteImport.update({
  id: '/answers/$answerId',
  path: '/answers/$answerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRouteWithChildren
  '/answers/$answerId': typeof AnswersAnswerIdRoute
  '/hashtag/$hashtag': typeof HashtagHashtagRoute
  '/profile/favorite-messages': typeof ProfileFavoriteMessagesRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers/$answerId': typeof AnswersAnswerIdRoute
  '/hashtag/$hashtag': typeof HashtagHashtagRoute
  '/profile/favorite-messages': typeof ProfileFavoriteMessagesRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRouteWithChildren
  '/answers/$answerId': typeof AnswersAnswerIdRoute
  '/hashtag/$hashtag': typeof HashtagHashtagRoute
  '/profile/favorite-messages': typeof ProfileFavoriteMessagesRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/profile'
    | '/answers/$answerId'
    | '/hashtag/$hashtag'
    | '/profile/favorite-messages'
    | '/profile/settings'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/answers/$answerId'
    | '/hashtag/$hashtag'
    | '/profile/favorite-messages'
    | '/profile/settings'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/profile'
    | '/answers/$answerId'
    | '/hashtag/$hashtag'
    | '/profile/favorite-messages'
    | '/profile/settings'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  AnswersAnswerIdRoute: typeof AnswersAnswerIdRoute
  HashtagHashtagRoute: typeof HashtagHashtagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/favorite-messages': {
      id: '/profile/favorite-messages'
      path: '/favorite-messages'
      fullPath: '/profile/favorite-messages'
      preLoaderRoute: typeof ProfileFavoriteMessagesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/hashtag/$hashtag': {
      id: '/hashtag/$hashtag'
      path: '/hashtag/$hashtag'
      fullPath: '/hashtag/$hashtag'
      preLoaderRoute: typeof HashtagHashtagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers/$answerId': {
      id: '/answers/$answerId'
      path: '/answers/$answerId'
      fullPath: '/answers/$answerId'
      preLoaderRoute: typeof AnswersAnswerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileFavoriteMessagesRoute: typeof ProfileFavoriteMessagesRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileFavoriteMessagesRoute: ProfileFavoriteMessagesRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProfileRoute: ProfileRouteWithChildren,
  AnswersAnswerIdRoute: AnswersAnswerIdRoute,
  HashtagHashtagRoute: HashtagHashtagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
