/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routes/__root'
import { Route as SearchRouteImport } from './../../app/routes/search'
import { Route as ProfileSettingsRouteImport } from './../../app/routes/profile-settings'
import { Route as ProfileRouteImport } from './../../app/routes/profile'
import { Route as FavoriteMessagesRouteImport } from './../../app/routes/favorite-messages'
import { Route as AboutRouteImport } from './../../app/routes/about'
import { Route as IndexRouteImport } from './../../app/routes/index'
import { Route as HashtagHashtagRouteImport } from './../../app/routes/hashtag.$hashtag'
import { Route as AnswersAnswerIdRouteImport } from './../../app/routes/answers.$answerId'
import { Route as ProfileProfileIdIndexRouteImport } from './../../app/routes/profile.$profileId.index'
import { Route as ProfileProfileIdVideosRouteImport } from './../../app/routes/profile.$profileId.videos'
import { Route as ProfileProfileIdMessagesRouteImport } from './../../app/routes/profile.$profileId.messages'
import { Route as ProfileProfileIdImagesRouteImport } from './../../app/routes/profile.$profileId.images'
import { Route as ProfileProfileIdFollowingsRouteImport } from './../../app/routes/profile.$profileId.followings'
import { Route as ProfileProfileIdFollowersRouteImport } from './../../app/routes/profile.$profileId.followers'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile-settings',
  path: '/profile-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteMessagesRoute = FavoriteMessagesRouteImport.update({
  id: '/favorite-messages',
  path: '/favorite-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HashtagHashtagRoute = HashtagHashtagRouteImport.update({
  id: '/hashtag/$hashtag',
  path: '/hashtag/$hashtag',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersAnswerIdRoute = AnswersAnswerIdRouteImport.update({
  id: '/answers/$answerId',
  path: '/answers/$answerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdIndexRoute = ProfileProfileIdIndexRouteImport.update({
  id: '/$profileId/',
  path: '/$profileId/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileProfileIdVideosRoute = ProfileProfileIdVideosRouteImport.update({
  id: '/$profileId/videos',
  path: '/$profileId/videos',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileProfileIdMessagesRoute =
  ProfileProfileIdMessagesRouteImport.update({
    id: '/$profileId/messages',
    path: '/$profileId/messages',
    getParentRoute: () => ProfileRoute,
  } as any)
const ProfileProfileIdImagesRoute = ProfileProfileIdImagesRouteImport.update({
  id: '/$profileId/images',
  path: '/$profileId/images',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileProfileIdFollowingsRoute =
  ProfileProfileIdFollowingsRouteImport.update({
    id: '/$profileId/followings',
    path: '/$profileId/followings',
    getParentRoute: () => ProfileRoute,
  } as any)
const ProfileProfileIdFollowersRoute =
  ProfileProfileIdFollowersRouteImport.update({
    id: '/$profileId/followers',
    path: '/$profileId/followers',
    getParentRoute: () => ProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorite-messages': typeof FavoriteMessagesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/profile-settings': typeof ProfileSettingsRoute
  '/search': typeof SearchRoute
  '/answers/$answerId': typeof AnswersAnswerIdRoute
  '/hashtag/$hashtag': typeof HashtagHashtagRoute
  '/profile/$profileId/followers': typeof ProfileProfileIdFollowersRoute
  '/profile/$profileId/followings': typeof ProfileProfileIdFollowingsRoute
  '/profile/$profileId/images': typeof ProfileProfileIdImagesRoute
  '/profile/$profileId/messages': typeof ProfileProfileIdMessagesRoute
  '/profile/$profileId/videos': typeof ProfileProfileIdVideosRoute
  '/profile/$profileId/': typeof ProfileProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorite-messages': typeof FavoriteMessagesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/profile-settings': typeof ProfileSettingsRoute
  '/search': typeof SearchRoute
  '/answers/$answerId': typeof AnswersAnswerIdRoute
  '/hashtag/$hashtag': typeof HashtagHashtagRoute
  '/profile/$profileId/followers': typeof ProfileProfileIdFollowersRoute
  '/profile/$profileId/followings': typeof ProfileProfileIdFollowingsRoute
  '/profile/$profileId/images': typeof ProfileProfileIdImagesRoute
  '/profile/$profileId/messages': typeof ProfileProfileIdMessagesRoute
  '/profile/$profileId/videos': typeof ProfileProfileIdVideosRoute
  '/profile/$profileId': typeof ProfileProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favorite-messages': typeof FavoriteMessagesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/profile-settings': typeof ProfileSettingsRoute
  '/search': typeof SearchRoute
  '/answers/$answerId': typeof AnswersAnswerIdRoute
  '/hashtag/$hashtag': typeof HashtagHashtagRoute
  '/profile/$profileId/followers': typeof ProfileProfileIdFollowersRoute
  '/profile/$profileId/followings': typeof ProfileProfileIdFollowingsRoute
  '/profile/$profileId/images': typeof ProfileProfileIdImagesRoute
  '/profile/$profileId/messages': typeof ProfileProfileIdMessagesRoute
  '/profile/$profileId/videos': typeof ProfileProfileIdVideosRoute
  '/profile/$profileId/': typeof ProfileProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/favorite-messages'
    | '/profile'
    | '/profile-settings'
    | '/search'
    | '/answers/$answerId'
    | '/hashtag/$hashtag'
    | '/profile/$profileId/followers'
    | '/profile/$profileId/followings'
    | '/profile/$profileId/images'
    | '/profile/$profileId/messages'
    | '/profile/$profileId/videos'
    | '/profile/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/favorite-messages'
    | '/profile'
    | '/profile-settings'
    | '/search'
    | '/answers/$answerId'
    | '/hashtag/$hashtag'
    | '/profile/$profileId/followers'
    | '/profile/$profileId/followings'
    | '/profile/$profileId/images'
    | '/profile/$profileId/messages'
    | '/profile/$profileId/videos'
    | '/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/favorite-messages'
    | '/profile'
    | '/profile-settings'
    | '/search'
    | '/answers/$answerId'
    | '/hashtag/$hashtag'
    | '/profile/$profileId/followers'
    | '/profile/$profileId/followings'
    | '/profile/$profileId/images'
    | '/profile/$profileId/messages'
    | '/profile/$profileId/videos'
    | '/profile/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FavoriteMessagesRoute: typeof FavoriteMessagesRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  SearchRoute: typeof SearchRoute
  AnswersAnswerIdRoute: typeof AnswersAnswerIdRoute
  HashtagHashtagRoute: typeof HashtagHashtagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-settings': {
      id: '/profile-settings'
      path: '/profile-settings'
      fullPath: '/profile-settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite-messages': {
      id: '/favorite-messages'
      path: '/favorite-messages'
      fullPath: '/favorite-messages'
      preLoaderRoute: typeof FavoriteMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hashtag/$hashtag': {
      id: '/hashtag/$hashtag'
      path: '/hashtag/$hashtag'
      fullPath: '/hashtag/$hashtag'
      preLoaderRoute: typeof HashtagHashtagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers/$answerId': {
      id: '/answers/$answerId'
      path: '/answers/$answerId'
      fullPath: '/answers/$answerId'
      preLoaderRoute: typeof AnswersAnswerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId/': {
      id: '/profile/$profileId/'
      path: '/$profileId'
      fullPath: '/profile/$profileId/'
      preLoaderRoute: typeof ProfileProfileIdIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$profileId/videos': {
      id: '/profile/$profileId/videos'
      path: '/$profileId/videos'
      fullPath: '/profile/$profileId/videos'
      preLoaderRoute: typeof ProfileProfileIdVideosRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$profileId/messages': {
      id: '/profile/$profileId/messages'
      path: '/$profileId/messages'
      fullPath: '/profile/$profileId/messages'
      preLoaderRoute: typeof ProfileProfileIdMessagesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$profileId/images': {
      id: '/profile/$profileId/images'
      path: '/$profileId/images'
      fullPath: '/profile/$profileId/images'
      preLoaderRoute: typeof ProfileProfileIdImagesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$profileId/followings': {
      id: '/profile/$profileId/followings'
      path: '/$profileId/followings'
      fullPath: '/profile/$profileId/followings'
      preLoaderRoute: typeof ProfileProfileIdFollowingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$profileId/followers': {
      id: '/profile/$profileId/followers'
      path: '/$profileId/followers'
      fullPath: '/profile/$profileId/followers'
      preLoaderRoute: typeof ProfileProfileIdFollowersRouteImport
      parentRoute: typeof ProfileRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileProfileIdFollowersRoute: typeof ProfileProfileIdFollowersRoute
  ProfileProfileIdFollowingsRoute: typeof ProfileProfileIdFollowingsRoute
  ProfileProfileIdImagesRoute: typeof ProfileProfileIdImagesRoute
  ProfileProfileIdMessagesRoute: typeof ProfileProfileIdMessagesRoute
  ProfileProfileIdVideosRoute: typeof ProfileProfileIdVideosRoute
  ProfileProfileIdIndexRoute: typeof ProfileProfileIdIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileProfileIdFollowersRoute: ProfileProfileIdFollowersRoute,
  ProfileProfileIdFollowingsRoute: ProfileProfileIdFollowingsRoute,
  ProfileProfileIdImagesRoute: ProfileProfileIdImagesRoute,
  ProfileProfileIdMessagesRoute: ProfileProfileIdMessagesRoute,
  ProfileProfileIdVideosRoute: ProfileProfileIdVideosRoute,
  ProfileProfileIdIndexRoute: ProfileProfileIdIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FavoriteMessagesRoute: FavoriteMessagesRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProfileSettingsRoute: ProfileSettingsRoute,
  SearchRoute: SearchRoute,
  AnswersAnswerIdRoute: AnswersAnswerIdRoute,
  HashtagHashtagRoute: HashtagHashtagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
