export const MAX_MESSAGE_BODY_LENGTH = 600;
export const MIN_MESSAGE_BODY_LENGTH = 2;

export const MAX_UPLOADED_IMAGES = 4;
export const MAX_IMAGE_SIZE_IN_BYTES = 262144; // 256 KB

export const MAX_UPLOADED_VIDEOS = 1;
export const MAX_VIDEO_SIZE_IN_BYTES = 52428800; // 50 MB
