/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routes/__root'
import { Route as AboutRouteImport } from './../../app/routes/about'
import { Route as mainIndexRouteImport } from './../../app/routes/(main)/index'
import { Route as mainAnswersAnswerIdRouteImport } from './../../app/routes/(main)/answers.$answerId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/(main)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAnswersAnswerIdRoute = mainAnswersAnswerIdRouteImport.update({
  id: '/(main)/answers/$answerId',
  path: '/answers/$answerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/': typeof mainIndexRoute
  '/answers/$answerId': typeof mainAnswersAnswerIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/': typeof mainIndexRoute
  '/answers/$answerId': typeof mainAnswersAnswerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/answers/$answerId': typeof mainAnswersAnswerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/' | '/answers/$answerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/' | '/answers/$answerId'
  id: '__root__' | '/about' | '/(main)/' | '/(main)/answers/$answerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  mainIndexRoute: typeof mainIndexRoute
  mainAnswersAnswerIdRoute: typeof mainAnswersAnswerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/answers/$answerId': {
      id: '/(main)/answers/$answerId'
      path: '/answers/$answerId'
      fullPath: '/answers/$answerId'
      preLoaderRoute: typeof mainAnswersAnswerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  mainIndexRoute: mainIndexRoute,
  mainAnswersAnswerIdRoute: mainAnswersAnswerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
