create schema if not exists "utils";

alter table "public"."messages" drop constraint "messages_body_check";

drop function if exists "public"."calculate_lexical_text_length"(lexical_node jsonb, result_length integer);

drop function if exists "public"."favorites_count"(public.profiles);

drop function if exists "public"."followers_count"(public.profiles);

drop function if exists "public"."followings_count"(public.profiles);

drop function if exists "public"."handle_new_user"();

drop function if exists "public"."is_follower"(public.profiles);

drop function if exists "public"."is_following"(public.profiles);

drop function if exists "public"."message_has_liked"(public.messages);

drop function if exists "public"."message_in_favorite"(public.messages);

drop function if exists "public"."message_likes_count"(public.messages);

drop function if exists "public"."messages_count"(public.profiles);

drop function if exists "public"."process_lexical_node_with_children"(lexical_node jsonb, result_length integer);

drop function if exists "public"."validate_message_body"(message_body jsonb);


  create table "public"."hashtags" (
    "id" bigint generated by default as identity not null,
    "date" timestamp with time zone not null default now(),
    "hashtag" text not null
      );


alter table "public"."hashtags" enable row level security;

alter table "public"."messages" alter column "id" set default extensions.uuid_generate_v1mc();

CREATE UNIQUE INDEX favorites_pkey ON public.favorites USING btree ("authorId", "messageId");

CREATE UNIQUE INDEX hashtags_pkey ON public.hashtags USING btree (id);

CREATE INDEX "likes_messageId_idx" ON public.likes USING btree ("messageId");

CREATE UNIQUE INDEX likes_pkey ON public.likes USING btree ("authorId", "messageId");

alter table "public"."favorites" add constraint "favorites_pkey" PRIMARY KEY using index "favorites_pkey";

alter table "public"."hashtags" add constraint "hashtags_pkey" PRIMARY KEY using index "hashtags_pkey";

alter table "public"."likes" add constraint "likes_pkey" PRIMARY KEY using index "likes_pkey";

alter table "public"."messages" add constraint "messages_body_check" CHECK (((utils.calculate_lexical_text_length(body) < 600) AND utils.validate_message_body(body))) not valid;

alter table "public"."messages" validate constraint "messages_body_check";

set check_function_bodies = off;

create or replace view "public"."followers_view" as  SELECT f."followerId",
    f."authorId",
    p.username,
    p.avatar,
    (EXISTS ( SELECT 1
           FROM public.followers
          WHERE ((followers."authorId" = auth.uid()) AND (followers."followerId" = p.id)))) AS "isFollowing"
   FROM (public.followers f
     JOIN public.profiles p ON ((p.id = f."authorId")));


create or replace view "public"."hashtags_month_top_view" as  SELECT hashtag,
    count(*) AS count
   FROM public.hashtags
  WHERE (date >= date_trunc('day'::text, (now() - '1 mon'::interval)))
  GROUP BY hashtag
  ORDER BY (count(*)) DESC
 LIMIT 20;


create or replace view "public"."hashtags_week_top_view" as  SELECT hashtag,
    count(*) AS count
   FROM public.hashtags
  WHERE (date >= date_trunc('day'::text, (now() - '7 days'::interval)))
  GROUP BY hashtag
  ORDER BY (count(*)) DESC
 LIMIT 20;


create or replace view "public"."messages_view" as  SELECT m."answerId",
    m."authorId",
    m.body,
    m.created,
    m."embeddedItems",
    m."embeddedType",
    m.id,
    m.updated,
    p.username,
    p.avatar,
    (EXISTS ( SELECT likes."messageId"
           FROM public.likes
          WHERE ((likes."messageId" = m.id) AND (likes."authorId" = auth.uid())))) AS "hasLiked",
    (EXISTS ( SELECT favorites."messageId"
           FROM public.favorites
          WHERE ((favorites."messageId" = m.id) AND (favorites."authorId" = auth.uid())))) AS "isFavorite",
    ( SELECT count(1) AS count
           FROM public.likes l
          WHERE (l."messageId" = m.id)) AS "likesCount",
    ( SELECT count(1) AS count
           FROM public.messages a
          WHERE (a."answerId" = m.id)) AS "answersCount"
   FROM (public.messages m
     JOIN public.profiles p ON ((p.id = m."authorId")));


create or replace view "public"."profiles_view" as  SELECT id,
    created,
    avatar,
    bio,
    username,
    displayname,
    (EXISTS ( SELECT f."authorId"
           FROM public.followers f
          WHERE ((f."authorId" = auth.uid()) AND (f."followerId" = p.id)))) AS "isFollowing",
    (EXISTS ( SELECT f."followerId"
           FROM public.followers f
          WHERE ((f."followerId" = auth.uid()) AND (f."authorId" = p.id)))) AS "isFollower",
    ( SELECT count(1) AS count
           FROM public.followers f
          WHERE (f."followerId" = p.id)) AS "followersCount",
    ( SELECT count(1) AS count
           FROM public.followers f
          WHERE (f."authorId" = p.id)) AS "followingsCount",
    ( SELECT count(1) AS count
           FROM public.favorites f
          WHERE (f."authorId" = auth.uid())) AS "favoritesCount",
    ( SELECT count(1) AS count
           FROM public.messages m
          WHERE (m."authorId" = p.id)) AS "messagesCount"
   FROM public.profiles p;


CREATE OR REPLACE FUNCTION utils.calculate_lexical_text_length(lexical_node jsonb)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
DECLARE
  acc int = 0;
  lexical_node_child jsonb;
  type text := lexical_node ->> 'type';
BEGIN
  if type = 'root' or type = 'paragraph' or type = 'link' or type = 'autolink' then
    for lexical_node_child IN select * from jsonb_array_elements((lexical_node -> 'children'))
    LOOP acc := acc + utils.calculate_lexical_text_length(lexical_node_child);
    end LOOP;

    return acc;

  elsif type = 'hashtag' or type = 'text' or type = 'user' or type = 'emoji' then
    return length(lexical_node ->> 'text');
  end if;

  return 0;
END;
$function$
;

CREATE OR REPLACE FUNCTION utils.extract_and_insert_hashtags(lexical_node jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  lexical_node_child jsonb;
  type text := lexical_node ->> 'type';
BEGIN
  if type = 'root' or type = 'paragraph' or type = 'link' or type = 'autolink' then
    FOR lexical_node_child IN SELECT * FROM jsonb_array_elements((lexical_node -> 'children'))
    LOOP
      perform utils.extract_and_insert_hashtags(lexical_node_child);
    END LOOP;

  elsif type = 'hashtag' then
    insert into public.hashtags (hashtag) values (lexical_node ->> 'text');
  end if;
END;
$function$
;

CREATE OR REPLACE FUNCTION utils.handle_new_message()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
  perform utils.extract_and_insert_hashtags(new.body);
  return new;
END;
$function$
;

CREATE OR REPLACE FUNCTION utils.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    json_value(new.raw_user_meta_data, '$.username' default 'anon_'||gen_random_uuid() on empty)
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION utils.validate_message_body(message_body jsonb)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$ select extensions.jsonb_matches_schema(
  schema := '
{
  "type": "object",
  "properties": {
    "type": { "type": "string", "const": "root" },
    "children": {
      "type": "array",
      "items": { "$ref": "#/definitions/Paragraph" }
    }
  },
  "required": ["type", "children"],
  "definitions": {
    "Paragraph": {
      "type": "object",
      "properties": {
        "type": { "type": "string", "const": "paragraph" },
        "children": {
          "type": "array",
          "items": {
            "oneOf": [
              { "$ref": "#/definitions/Text" },
              { "$ref": "#/definitions/Link" },
              { "$ref": "#/definitions/Autolink" },
              { "$ref": "#/definitions/Hashtag" },
              { "$ref": "#/definitions/User" },
              { "$ref": "#/definitions/Emoji" }
            ]
          }
        }
      },
      "required": ["type", "children"]
    },
    "Text": {
      "type": "object",
      "properties": {
        "type": { "type": "string", "const": "text" },
        "text": { "type": "string" },
        "format": { "type": "number" }
      },
      "required": ["type", "text", "format"]
    },
    "Link": {
      "type": "object",
      "properties": {
        "type": { "type": "string", "const": "link" },
        "url": { "type": "string" },
        "children": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/Text"
          }
        }
      },
      "required": ["type", "url", "children"]
    },
    "Autolink": {
      "type": "object",
      "properties": {
        "type": { "type": "string", "const": "autolink" },
        "url": { "type": "string" },
        "children": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/Text"
          }
        }
      },
      "required": ["type", "url", "children"]
    },
    "Hashtag": {
      "type": "object",
      "properties": {
        "type": { "type": "string", "const": "hashtag" },
        "text": { "type": "string" },
        "format": { "type": "number" }
      },
      "required": ["type", "text", "format"]
    },
    "User": {
      "type": "object",
      "properties": {
        "type": { "type": "string", "const": "user" },
        "text": { "type": "string" },
        "format": { "type": "number" },
        "id": { "type": "string" },
        "username": { "type": "string" }
      },
      "required": ["type", "text", "format", "id", "username"]
    },
    "Emoji": {
      "type": "object",
      "properties": {
        "type": { "type": "string", "const": "emoji" },
        "text": { "type": "string" },
        "unicode": { "type": "string" },
        "label": { "type": "string" }
      },
      "required": ["type", "text", "unicode", "label"]
    }
  }
}',
  instance := message_body
);$function$
;

grant delete on table "public"."hashtags" to "anon";

grant insert on table "public"."hashtags" to "anon";

grant references on table "public"."hashtags" to "anon";

grant select on table "public"."hashtags" to "anon";

grant trigger on table "public"."hashtags" to "anon";

grant truncate on table "public"."hashtags" to "anon";

grant update on table "public"."hashtags" to "anon";

grant delete on table "public"."hashtags" to "authenticated";

grant insert on table "public"."hashtags" to "authenticated";

grant references on table "public"."hashtags" to "authenticated";

grant select on table "public"."hashtags" to "authenticated";

grant trigger on table "public"."hashtags" to "authenticated";

grant truncate on table "public"."hashtags" to "authenticated";

grant update on table "public"."hashtags" to "authenticated";

grant delete on table "public"."hashtags" to "postgres";

grant insert on table "public"."hashtags" to "postgres";

grant references on table "public"."hashtags" to "postgres";

grant select on table "public"."hashtags" to "postgres";

grant trigger on table "public"."hashtags" to "postgres";

grant truncate on table "public"."hashtags" to "postgres";

grant update on table "public"."hashtags" to "postgres";

grant delete on table "public"."hashtags" to "service_role";

grant insert on table "public"."hashtags" to "service_role";

grant references on table "public"."hashtags" to "service_role";

grant select on table "public"."hashtags" to "service_role";

grant trigger on table "public"."hashtags" to "service_role";

grant truncate on table "public"."hashtags" to "service_role";

grant update on table "public"."hashtags" to "service_role";


  create policy "Enable read access for all users"
  on "public"."hashtags"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."likes"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER on_message_created AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION utils.handle_new_message();

drop trigger if exists "on_auth_user_created" on "auth"."users";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION utils.handle_new_user();


